// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZRuj_v2yqdtb6NWyoqD7j2_pXroS6Qi8',
    appId: '1:643169100084:web:b9c789cfd04e34365c4561',
    messagingSenderId: '643169100084',
    projectId: 'auth-march-c153f',
    authDomain: 'auth-march-c153f.firebaseapp.com',
    storageBucket: 'auth-march-c153f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYHfn9DCRV4ebOrsVlMfRZ_kR9Bndz5uo',
    appId: '1:643169100084:android:038ee9a4f957c7a85c4561',
    messagingSenderId: '643169100084',
    projectId: 'auth-march-c153f',
    storageBucket: 'auth-march-c153f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-0j_heahE0W8wj3mlHr-QUYooQsYESyI',
    appId: '1:643169100084:ios:7e769c2da8ffe5c35c4561',
    messagingSenderId: '643169100084',
    projectId: 'auth-march-c153f',
    storageBucket: 'auth-march-c153f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-0j_heahE0W8wj3mlHr-QUYooQsYESyI',
    appId: '1:643169100084:ios:7e769c2da8ffe5c35c4561',
    messagingSenderId: '643169100084',
    projectId: 'auth-march-c153f',
    storageBucket: 'auth-march-c153f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZRuj_v2yqdtb6NWyoqD7j2_pXroS6Qi8',
    appId: '1:643169100084:web:a31daec6d351001d5c4561',
    messagingSenderId: '643169100084',
    projectId: 'auth-march-c153f',
    authDomain: 'auth-march-c153f.firebaseapp.com',
    storageBucket: 'auth-march-c153f.firebasestorage.app',
  );
}
